# Generated by Django 3.0.6 on 2020-06-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_price',
            new_name='job_budget',
        ),
    ]
