# Generated by Django 3.0.6 on 2020-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200624_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paied',
            field=models.BooleanField(default=False),
        ),
    ]
