# Generated by Django 3.0.6 on 2020-06-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_paied'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='url_payment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agro_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
